import Head from "next/head";
import styles from "@/styles/Home.module.css";

import { Image } from 'antd/lib';
import Title from "antd/lib/typography/Title";
import DownloadBtn from "./components/DownloadBtn/DownloadBtn";
import UploadForm from "./components/UploadForm/UploadForm";
import TypeErrorMessage from "./components/TypeErrorMessage/TypeErrorMessage";
import LoadingBlock from "./components/LoadingBlock/LoadingBlock";
import SwitchOnlyBasePoints from "./components/SwitchOnlyBasePoints/SwitchOnlyBasePoints";

export default function Home() {

  return (
    <>
      <Head>
        <title>MOOE to XLSX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <Image className={styles.mainImg} preview={false} src="img/svg/ak.svg"></Image>

        <Title className={"h1"}><span className={"titleBlock"}>
          <span>.mooe</span> / <span>.xlsx</span></span>
        </Title>

        <div className={styles["main-block"]}>

          <UploadForm />

          <TypeErrorMessage />

          <LoadingBlock />

          <SwitchOnlyBasePoints />

          <DownloadBtn />

        </div>

        {/* <button onClick={exportExcel}>Download Excel</button> */}
      </main>
    </>
  );
}
